# Site Settings
lang: en
title: French -er Verb Conjugation
tagline: French Regular -er Verb Conjugation
description: >
  A quizzing application for practice with regular -er verbs
baseurl: "/er-conjugate"
url: "https://asherhe.github.io"
permalink: pretty

plugins:
  - jekyll-seo-tag
  - kramdown-parser-gfm

livereload: true

markdown: kramdown
